spring:
  cloud:
    gateway:
      routes:        
        - id: microservices-beer-service
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/beers/*
            - Path=/api/v1/upc/*
        - id: mircoservices-inventory-service
          uri: http://localhost:8072
          predicates:
            - Path=/api/v1/beers/*/inventory
        - id: mircoservices-order-service
          uri: http://localhost:8073
          predicates:
            - Path=/api/v1/customers/**

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
        enabled: true
